spring.profiles.active=production,test
SECRET_KEY=${JWT_SECRET_KEY}
v1API=/api/v1
server.port=${PORT:8080}
# comma separated list of frontend urls
allowedOrigins=${ALLOWED_ORIGINS:http://localhost:3000}
